# Session 7: Introduction to ML - Classification

## Demo 2: Supplement - Customer Churn Dataset Preprocessing

Data preprocessing of customer service churn dataset (https://www.kaggle.com/blastchar/telco-customer-churn) for classification

In [2]:
# The first part is to import the required packages
import numpy #For array operations
import pandas as pd #DataFrame
import numpy as np

# Load the data (can be found on https://www.kaggle.com/blastchar/telco-customer-churn)
customer_data = pd.read_csv('./data/Telco-Customer-Churn.csv')
customer_data.head()
customer_data = customer_data.replace(r'^\s*$', np.nan, regex=True) #replace empty strings with NaN

# Drop null/error/empty values
# print(customer_data.isnull().sum()) #check null values
customer_data.dropna(inplace=True)
# print(customer_data.isnull().sum()) #check null values again

# Convert TotalCharges to numeric
customer_data['TotalCharges'] = pd.to_numeric(customer_data['TotalCharges'])
customer_data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
# Changes all values indicating 'no service' to label 'No'

customer_data['MultipleLines']  = customer_data['MultipleLines'].replace({'No phone service' : 'No'})
customer_data['OnlineSecurity']  = customer_data['OnlineSecurity'].replace({'No internet service' : 'No'})
customer_data['OnlineBackup']  = customer_data['OnlineBackup'].replace({'No internet service' : 'No'})
customer_data['DeviceProtection']  = customer_data['DeviceProtection'].replace({'No internet service' : 'No'})
customer_data['TechSupport']  = customer_data['TechSupport'].replace({'No internet service' : 'No'})
customer_data['StreamingTV']  = customer_data['StreamingTV'].replace({'No internet service' : 'No'})
customer_data['StreamingMovies']  = customer_data['StreamingMovies'].replace({'No internet service' : 'No'})

In [7]:
# Transform categorical values to dummies
columns_to_transform = customer_data.columns[1:]
customer_dummies = pd.get_dummies(customer_data[columns_to_transform], drop_first = True)
customer_dummies.to_csv('./data/Telco-Customer-Churn_dummies.csv')
customer_dummies.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_Yes,InternetService_Fiber optic,...,TechSupport_Yes,StreamingTV_Yes,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,0,1,29.85,29.85,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,1
3,0,45,42.30,1840.75,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,0,2,70.70,151.65,0,0,0,1,0,1,...,0,0,0,0,0,1,0,1,0,1